
# THIS IS A TEMPLATE. REPLACE ALL VALUES IN QUOTES '' WITH YOUR PERSONAL INFO. (do not remove the quotes '')

# twitch
app_id = 'YOUR_APP_ID'
app_secret = 'YOUR_APP_SECRET'
username = 'YOUR_TWITCH_USERNAME'

# adafruit IO
ADAFRUIT_IO_KEY = 'YOUR_ADAFRUIT_IO_KEY'
ADAFRUIT_IO_USERNAME = 'YOUR_ADAFRUIT_IO_USERNAME'